### ISSUE TITLE
Overwriting files

### ISSUE THREAD

**Issue by bindestriche** [Tatsh/ffmpeg-progress#12]
Thanks for the nice tool.
I noticed when you interrupt a process and restart it again, you are not prompted if you want to overwrite the file or not.
of course I can pass `-y`, otherwise the script hangs forever with no warning.

**Comment by Tatsh** [comment]
This is not going to prompt as it is intended to be used as a library. Interactivity is out of the scope of this project.

If you are using this with an interactive UI of any kind you need to implement the prompting functionality and still pass `-y` or delete the file beforehand.
