### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by saurabhmarne9595** [Tatsh/ffmpeg-progress#9]
ffmpeg version 3.4.6-0ubuntu0.18.04.1
Python 3.6.9 (default, Nov  7 2019, 10:44:02)

>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saurabhnew/website_ffmpeg_project/ffmpeg_progress.py", line 4, in <module>
    from ffmpeg_progress import start
ImportError: cannot import name 'start'

Same issue on,
ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
Python 3.5.2 (default, Apr 16 2020, 17:47:17)

**Comment by Tatsh** [comment]
You have the same filename as the original module. You should rename your file to something different.

**Comment by saurabhmarne9595** [comment]
yes, got it. there was a different file with same name so error was on that system too. Thank you.
